### ISSUE TITLE
Package testing

### ISSUE THREAD

**Issue by fluvf** [networkcobwebs/minecraft-server-manager#45]
I'm planning on adding tests for the project, so few questions before I get started
- I'm thinking about using [tape](https://github.com/substack/tape), mainly because I'm familiar with it and it's simple to use
- What tests should be added? I was thinking about adding tests for both the api and the minecrarft-server, but only testing the api could be enough as those should be the only functions exposed to the web interface / needed to run things.
- Adding proper tests should make the debug flags obsolete. With this the code could be made less verbose overall, as far as `console.log()` goes. Maybe add a `verbose = true` argument to the api and move all messages there. This would also avoid console spam if not explicitly requested

**Comment by nickrnet** [comment]
1. I would lean [Mocha](https://mochajs.org/) or [Jasmine](https://jasmine.github.io/) tests personally as that is what I am most familiar with and there's lots of docs. Mocha allows async tests, and lots of IDE's have built-in runners that parse the results. I haven't had to go crazy-complicated with Mocha yet in other projects, I just use its built-in assertions out of the box.

Honestly as far as testing frameworks go, tests in general here are lacking. If you'd like to take a swag at a few using tape, we can review in a branch before we fully commit to it. And I'm not against multiple frameworks, either.

2. I would test minecraft-api for now as it is the most user-facing. minecraft-server has some, well, hiccups in its serial-ness, which I have a thought on but haven't logged an issue yet as I'm still processing how it would work. Some of that trickles through to the API, but the API is where to start.

3. I'm personally hesitant to remove most of the `console.logs`, I've run into too many timing issues that are painful to retype, hence the debug flags around most of them. The debug flag is "the explicit request." If you're getting console spam, those should be looked into why they are happening without the debug flag. In general system administration (IME), logging is helpful, so I tried to leave the "important" messages without the flag.

**Comment by fluvf** [comment]
I think mocha has been established as the preferred test engine
