### ISSUE TITLE
Switch server to use RCON for commands and queries

### ISSUE THREAD

**Issue by nickrnet** [networkcobwebs/minecraft-server-manager#64]
Instead of attaching to the server jar's stdin and stdout for commands and queries, use an RCON client. https://www.npmjs.com/package/rcon-client and https://www.npmjs.com/package/rcon.js look promising. This would hopefully get rid of some of the output buffering bugs and/or complexity.

Testing needs to include what happens when in-game players/ops do things that may conflict with or interrupt RCON commands.

**Comment by fluvf** [comment]
Sorry for disappearing and for my lack of communication
I worked on something similar to this a while ago on [this branch](https://github.com/Fluvf/minecraft-server-manager/tree/srvh) and the code's ready and working (as far as I know), but lacking tests
I've been busy with a different project, but once I'm done there I intend to come back to this one
Won't promise anything tho, I wasn't exactly planning on going silent for as long as I did either 😅
